name: Build

on:
  pull_request:
  push:
    paths-ignore:
      - 'README.md'
    branches:
      - '1.10'

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          #- macos-latest
          - ubuntu-20.04
          #- windows-latest
        ocaml-version:
          #- 4.11.0
          #- 4.10.1
          - 4.14.0
          #- 4.09.1
          #- 4.08.1

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Use OCaml ${{ matrix.ocaml-version }}
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: ${{ matrix.ocaml-version }}

      - run: opam pin add Lama.dev . --no-action
      - run: opam depext Lama.dev --yes --with-test
      - run: opam install . --deps-only --with-test
      - run: opam exec -- make #dune build
      - run: opam exec -- make regression # dune runtest
